#!/bin/sh

. /warewulf/config

if test -f "/etc/sysconfig/selinux"; then
    . /etc/sysconfig/selinux
else
    echo "Skipping SELinux configuration: Host config not found: /etc/sysconfig/selinux"
    exit
fi

if test "$SELINUX" == "disabled"; then
    echo "Skipping SELinux setup per /etc/sysconfig/selinux"
    exit
fi

if grep -q "selinux=0" /proc/cmdline; then
    echo "Skipping SELinux setup per kernel command line"
    exit
fi

ROOTFSTYPE=`stat -f -c "%T" /`
if test "$ROOTFSTYPE" == "initramfs"; then
    echo "Skipping SELinux configuration: / is ${ROOTFSTYPE}"
    if test "$SELINUX" != "disabled"; then
        echo "WARNING: SELinux prep is being skipped, but SELinux is enabled on host! This may"
        echo "WARNING: cause the system to not work properly. Try setting 'Root=tmpfs'"
        sleep 5
    fi
    exit
fi

echo "Setting up SELinux"
/sbin/load_policy -i
/sbin/restorecon -r /
