---
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron:  '05 00 * * *'

jobs:
  update_tag:
    name: Update the nightly tag
    runs-on: ubuntu-latest
    steps:
      - name: update tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/nightly',
              sha: context.sha
            })
