---
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron:  '05 00 * * *'

jobs:
  update_tag:
    name: Update the nightly tag
    runs-on: ubuntu-latest
    steps:
      - name: update tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/nightly',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/nightly',
                sha: context.sha
              });
            })
