---
name: release

on:
  release:
    types:
      - published

jobs:
  dist:
    name: Checkout code and build tar.gz
    runs-on: ubuntu-latest
    steps:
      - name: Set the version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build spec and dist
        run: |
          make warewulf.spec dist

      - name: Upload spec
        uses: actions/upload-artifact@v3
        with:
          name: warewulf.spec
          path: warewulf.spec

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: warewulf-${{ env.VERSION }}.tar.gz
          path: warewulf-${{ env.VERSION }}.tar.gz

  rpm:
      name: Build RPMs
      needs: dist
      runs-on: ubuntu-latest
      container:
        image: rockylinux/rockylinux:8
        options: --privileged
      strategy:
        matrix:
          target: ['rocky+epel-8-x86_64', 'centos+epel-7-x86_64', 'opensuse-leap-15.5-x86_64']
      steps:
        - name: Install EPEL
          run: dnf -y install epel-release

        - name: Install mock and rpm-build
          run: |
            dnf -y install mock rpm-build
            echo "config_opts['print_main_output'] = True" >>/etc/mock/site-defaults.cfg

        - name: Download spec
          uses: actions/download-artifact@v3
          with:
            name: warewulf.spec

        - name: Set the expected version
          run: |
            echo "EXPECTED_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

        - name: Download dist
          uses: actions/download-artifact@v3
          with:
            name: warewulf-${{ env.EXPECTED_VERSION }}.tar.gz

        - name: Set the version and release
          run: |
            VERSION=$(rpm -q --qf "%{VERSION}\n" --specfile warewulf.spec)
            RELEASE=$(rpm -q --qf "%{RELEASE}\n" --specfile warewulf.spec | cut -d. -f1-2)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
            echo "RELEASE=${RELEASE}" >> $GITHUB_ENV

        - name: Build RPMs
          run: mock -r ${{ matrix.target }} --rebuild --spec=warewulf.spec --sources=.

        - name: Upload RPMs
          uses: actions/upload-artifact@v3
          with:
            name: warewulf-${{ env.VERSION }}-${{ env.RELEASE }}
            path: /var/lib/mock/${{ matrix.target }}/result/warewulf-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm

        - name: Upload Assets To Release
          if: "!github.event.release.prerelease"
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: 'warewulf-${{ env.VERSION }}.tar.gz;warewulf-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm'
            draft: false
            update_latest_release: true
            tags: true

        - name: Upload Assets To Pre-Release
          if: "github.event.release.prerelease"
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: 'warewulf-${{ env.VERSION }}.tar.gz;warewulf-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm'
            draft: false
            update_latest_release: false
            prerelease: true
            tags: true
